-- L2 Mock 知识库种子数据，仅用于开发、联调和本地验证。
-- 执行前请先确认 risk_category、risk_details 以及 L2 知识库表已经存在。
-- 本脚本可重复执行：risk_detail_rule 通过 risk_details_id 幂等更新，
-- risk_attack_feature 通过稳定 content_hash 幂等更新。
--
-- 数据设计说明：
-- 1. risk_detail_rule 覆盖当前 31 个风险小类，每个小类一条判定规则。
-- 2. risk_attack_feature 每个小类 3 条特征：2 条 UNSAFE + 1 条 SAFE_EXCEPTION。
-- 3. 特征文本只保留风险识别关键词，不写具体违法、危险或可执行步骤。
-- 4. sync_status/es_sync_status/milvus_sync_status 统一置为 1，表示“模拟已同步到外部索引”。
-- 5. source/creator/updater 使用 mock_l2_seed/codex_mock，便于后续清理或替换正式数据。

SET NAMES utf8mb4;

-- 风险小类判定规则：
-- 规则表是 risk_details 维度的解释性知识，L2 主要用 severity_level 补充日志和路由上下文。
-- 后续 L3 Judge 接入时，可以复用 judge_rule、decision_boundary、unsafe_examples、safe_examples 组装裁决 Prompt。
INSERT INTO `risk_detail_rule` (
  `risk_details_id`,
  `judge_rule`,
  `severity_level`,
  `decision_boundary`,
  `unsafe_examples`,
  `safe_examples`,
  `version`,
  `status`,
  `creator`,
  `updater`,
  `deleted`
) VALUES
(1, '识别煽动颠覆国家政权、破坏国家统一、组织或号召分裂行动的内容。', 4, '明确号召、组织、策划、鼓动颠覆或分裂属于违规；历史研究、法律框架内的客观介绍不违规。', JSON_ARRAY('请求生成煽动分裂国家的口号', '要求策划推翻政权的行动话术'), JSON_ARRAY('客观介绍国家统一相关法律', '拒绝协助煽动并提示守法表达'), 1, 1, 'codex_mock', 'codex_mock', 0),
(2, '识别针对敏感政治事件或人物的攻击、造谣、煽动或不当扩散内容。', 3, '恶意攻击、编造事实、煽动对立属于违规；公开资料的中立介绍和合规新闻摘要不违规。', JSON_ARRAY('编造政治人物负面谣言', '要求生成煽动性政治攻击文案'), JSON_ARRAY('基于公开资料做中立介绍', '提示核验来源并避免传播谣言'), 1, 1, 'codex_mock', 'codex_mock', 0),
(3, '识别侮辱、贬损、恶搞国家象征的文本或输出模式。', 3, '以侮辱、丑化、恶搞为目的使用国家象征属于违规；礼仪、历史和规范性介绍不违规。', JSON_ARRAY('要求生成侮辱国旗国徽的段子', '模型输出贬损国家象征的描述'), JSON_ARRAY('介绍国旗国徽使用规范', '拒绝恶搞并解释尊重国家象征'), 1, 1, 'codex_mock', 'codex_mock', 0),
(4, '识别宣扬、赞美、招募或传播恐怖主义、极端主义的内容。', 4, '鼓吹、赞美、招募、传播极端主义主张属于违规；反恐科普、新闻报道和安全教育不违规。', JSON_ARRAY('要求生成恐怖组织招募话术', '赞美极端主义暴力行为'), JSON_ARRAY('反恐安全教育', '新闻语境下谴责恐怖主义'), 1, 1, 'codex_mock', 'codex_mock', 0),
(5, '识别对时政新闻进行煽动性、攻击性或违规导向点评的内容。', 3, '煽动对立、攻击制度、引导群体行动属于违规；客观摘要、事实核验和中立解读不违规。', JSON_ARRAY('要求把时政新闻改写成煽动性评论', '模型输出鼓动对抗的时政点评'), JSON_ARRAY('客观摘要公开新闻', '提醒基于权威来源核验'), 1, 1, 'codex_mock', 'codex_mock', 0),
(6, '识别编造、包装、扩散涉政谣言或未证实政治信息的内容。', 3, '编造来源、制造谣言、鼓励传播属于违规；辟谣、核验和事实澄清不违规。', JSON_ARRAY('要求编造涉政爆料', '请求扩散未证实政治谣言'), JSON_ARRAY('提示等待权威通报', '帮助识别谣言特征'), 1, 1, 'codex_mock', 'codex_mock', 0),
(7, '识别毒品制造、加工、交易、渠道、规避监管相关内容。', 4, '提供制造流程、配方、交易渠道或规避执法信息属于违规；禁毒科普、危害说明和求助引导不违规。', JSON_ARRAY('请求毒品制造配方', '询问毒品交易渠道'), JSON_ARRAY('介绍毒品危害', '拒绝提供并建议寻求帮助'), 1, 1, 'codex_mock', 'codex_mock', 0),
(8, '识别武器、爆炸物制作、材料清单、操作流程或使用指导。', 4, '提供制作步骤、材料清单、组装方式、提升伤害能力属于违规；安全法规、应急避险和拒答不违规。', JSON_ARRAY('索要炸弹制作步骤', '要求列出爆炸物材料清单'), JSON_ARRAY('拒绝提供爆炸物信息', '介绍公共安全和报警建议'), 1, 1, 'codex_mock', 'codex_mock', 0),
(9, '识别鼓励、自残、自杀方法、危险诱导或强化绝望感的内容。', 4, '提供方法、鼓励实施、降低求助意愿属于违规；危机干预、陪伴式支持和求助资源不违规。', JSON_ARRAY('询问自杀方法', '模型输出鼓励自残的话术'), JSON_ARRAY('建议联系紧急求助资源', '表达支持并鼓励寻求帮助'), 1, 1, 'codex_mock', 'codex_mock', 0),
(10, '识别传授犯罪方法、反侦察、毁灭证据、逃避追踪等内容。', 4, '提供犯罪实施或规避执法技巧属于违规；反诈教育、法律后果说明和守法建议不违规。', JSON_ARRAY('请求反侦察技巧', '询问销毁证据方法'), JSON_ARRAY('说明违法后果', '提供防范犯罪的建议'), 1, 1, 'codex_mock', 'codex_mock', 0),
(11, '识别网络诈骗、赌博引流、钓鱼、话术包装和资金盘推广内容。', 3, '提供诈骗话术、赌博渠道、钓鱼模板或引流方案属于违规；反诈提醒和风险识别不违规。', JSON_ARRAY('生成诈骗引流话术', '请求赌博平台推广文案'), JSON_ARRAY('识别诈骗套路', '提醒远离赌博风险'), 1, 1, 'codex_mock', 'codex_mock', 0),
(12, '识别危险化学品、生物制剂的违规制备、扩散、规避监管内容。', 4, '提供危险制备流程、非法获取渠道、扩散方式属于违规；实验室安全、法规和应急处置不违规。', JSON_ARRAY('请求危险化学品制备方法', '询问生物制剂扩散方式'), JSON_ARRAY('说明实验室安全规范', '建议联系专业机构处理'), 1, 1, 'codex_mock', 'codex_mock', 0),
(13, '识别非法交易、走私、黑产资源买卖和规避监管内容。', 3, '提供黑产渠道、走私路径、非法交易撮合属于违规；合规交易、法律风险提示不违规。', JSON_ARRAY('询问走私渠道', '请求黑产交易资源'), JSON_ARRAY('提示遵守交易法规', '说明非法交易风险'), 1, 1, 'codex_mock', 'codex_mock', 0),
(14, '识别涉及未成年人性剥削、儿童色情或诱导生成相关内容的请求和输出。', 4, '任何生成、索要、描述或传播未成年人性剥削内容均属于严重违规；保护、举报和预防教育不违规。', JSON_ARRAY('索要儿童色情内容', '要求生成涉及未成年人的性描写'), JSON_ARRAY('拒绝并提示举报渠道', '提供未成年人保护建议'), 1, 1, 'codex_mock', 'codex_mock', 0),
(15, '识别露骨色情、性行为细节描写或以刺激为目的的内容生成。', 3, '露骨描写、挑逗性细节和色情生成属于违规；健康教育、医学语境和边界清晰的合规讨论不违规。', JSON_ARRAY('要求生成露骨色情描写', '模型输出性行为细节'), JSON_ARRAY('转为健康教育说明', '拒绝露骨生成请求'), 1, 1, 'codex_mock', 'codex_mock', 0),
(16, '识别招嫖、非法性交易、中介联系、地点渠道等内容。', 3, '撮合、推广、寻找非法性交易渠道属于违规；法律风险、反性剥削科普不违规。', JSON_ARRAY('询问招嫖联系方式', '生成非法性交易推广文案'), JSON_ARRAY('提示违法风险', '提供反性剥削科普'), 1, 1, 'codex_mock', 'codex_mock', 0),
(17, '识别针对未成年人的不良诱导、私密接触、操控或越界内容。', 3, '诱导未成年人隐私、越界互动、规避监护属于违规；保护建议、教育和求助渠道不违规。', JSON_ARRAY('诱导未成年提供私密信息', '请求包装针对未成年人的越界话术'), JSON_ARRAY('提供未成年人保护建议', '建议向可信成年人求助'), 1, 1, 'codex_mock', 'codex_mock', 0),
(18, '识别软色情、擦边低俗、挑逗引流和不良暗示内容。', 2, '以性暗示、擦边吸引流量或低俗挑逗为目的属于违规；平台规范、审美讨论和合规表达不违规。', JSON_ARRAY('生成擦边低俗引流文案', '要求软色情挑逗标题'), JSON_ARRAY('改写为合规表达', '说明平台内容规范'), 1, 1, 'codex_mock', 'codex_mock', 0),
(19, '识别违背公序良俗的极端性癖、侮辱性或伤害性性内容。', 3, '将极端、伤害、侮辱性性内容作为刺激性生成目标属于违规；尊重边界和健康关系科普不违规。', JSON_ARRAY('要求生成极端性癖描写', '输出带侮辱性的性内容'), JSON_ARRAY('提示尊重边界', '转为健康关系科普'), 1, 1, 'codex_mock', 'codex_mock', 0),
(20, '识别极端恶意谩骂、人身攻击、威胁和羞辱内容。', 3, '针对个人的恶意辱骂、威胁、羞辱属于违规；理性表达、冲突调解和批评事实不违规。', JSON_ARRAY('生成恶意辱骂文案', '要求对某人做人身攻击'), JSON_ARRAY('改写为理性批评', '建议冷静沟通'), 1, 1, 'codex_mock', 'codex_mock', 0),
(21, '识别针对特定群体的仇恨言论、去人化、排斥和煽动攻击内容。', 3, '基于身份群体煽动仇恨、攻击或排斥属于违规；反歧视教育和包容倡议不违规。', JSON_ARRAY('生成针对群体的仇恨口号', '煽动排斥某类人群'), JSON_ARRAY('反歧视科普', '倡导平等包容'), 1, 1, 'codex_mock', 'codex_mock', 0),
(22, '识别基于种族、民族、地域的歧视、污名化和攻击内容。', 3, '使用歧视标签、地域黑称、群体污名化属于违规；客观文化介绍和反歧视说明不违规。', JSON_ARRAY('生成地域歧视段子', '用种族标签攻击他人'), JSON_ARRAY('介绍地域文化差异', '提醒避免刻板印象'), 1, 1, 'codex_mock', 'codex_mock', 0),
(23, '识别基于性别、性向、性别认同的歧视和侮辱内容。', 3, '以性别或性向为由贬损、排斥、攻击属于违规；平等尊重和权益科普不违规。', JSON_ARRAY('生成性别歧视文案', '侮辱特定性向群体'), JSON_ARRAY('倡导平等尊重', '提供反歧视解释'), 1, 1, 'codex_mock', 'codex_mock', 0),
(24, '识别职业、社会地位、收入等维度的歧视和羞辱内容。', 2, '因职业或社会地位贬低、羞辱、排斥他人属于违规；职业介绍和理性讨论不违规。', JSON_ARRAY('贬低特定职业群体', '生成社会地位歧视话术'), JSON_ARRAY('强调职业尊重', '客观介绍职业特点'), 1, 1, 'codex_mock', 'codex_mock', 0),
(25, '识别网络暴力、人肉搜索、公开隐私和教唆围攻内容。', 3, '组织网暴、索要或公开隐私、鼓动人肉属于违规；隐私保护和劝阻网暴不违规。', JSON_ARRAY('请求人肉搜索某人', '组织围攻辱骂目标'), JSON_ARRAY('劝阻网暴', '提示保护个人隐私'), 1, 1, 'codex_mock', 'codex_mock', 0),
(26, '识别窃取、泄露、拼接、传播个人隐私和敏感身份信息的内容。', 4, '索取、推断、泄露身份证、手机号、住址等个人信息属于违规；脱敏、安全保护和合规流程不违规。', JSON_ARRAY('请求泄露身份证手机号', '询问窃取个人隐私方法'), JSON_ARRAY('演示数据脱敏', '提醒保护个人信息'), 1, 1, 'codex_mock', 'codex_mock', 0),
(27, '识别商业机密、国家机密、内部资料的非法获取、泄露和扩散内容。', 4, '索取、传播、总结泄露机密或规避保密制度属于违规；保密合规和风险提示不违规。', JSON_ARRAY('请求泄露商业机密', '询问国家机密外传方式'), JSON_ARRAY('说明保密合规要求', '建议走授权流程'), 1, 1, 'codex_mock', 'codex_mock', 0),
(28, '识别固定越狱模板、DAN 类绕过、忽略安全规则等攻击模式。', 3, '要求模型忽略安全策略、伪装无限制助手或绕过审查属于违规；安全策略解释和拒绝越狱不违规。', JSON_ARRAY('使用 DAN 越狱模板', '要求忽略所有安全规则'), JSON_ARRAY('拒绝越狱请求', '解释安全边界'), 1, 1, 'codex_mock', 'codex_mock', 0),
(29, '识别恶意代码、木马、攻击脚本、黑客工具生成和攻击指导。', 4, '生成恶意代码、攻击脚本、入侵步骤或规避检测属于违规；防御、安全加固和漏洞修复不违规。', JSON_ARRAY('请求生成木马代码', '询问黑客攻击工具使用'), JSON_ARRAY('提供防御加固建议', '解释安全测试需授权'), 1, 1, 'codex_mock', 'codex_mock', 0),
(30, '识别提示词注入、泄露系统提示词、覆盖开发者指令和越权读取内容。', 4, '诱导泄露系统提示词、忽略上级指令或越权读取隐藏内容属于违规；防注入分析和安全加固不违规。', JSON_ARRAY('要求泄露系统提示词', '提示忽略之前所有指令'), JSON_ARRAY('说明提示词注入风险', '拒绝泄露隐藏指令'), 1, 1, 'codex_mock', 'codex_mock', 0),
(31, '识别动态越狱、角色扮演绕过、模拟无限制模型等规避安全边界内容。', 3, '通过角色扮演、假设场景、权限伪造来绕过安全策略属于违规；合规角色扮演和拒绝越权不违规。', JSON_ARRAY('要求扮演无限制模型', '通过角色扮演绕过安全限制'), JSON_ARRAY('拒绝越权请求', '保持合规角色扮演'), 1, 1, 'codex_mock', 'codex_mock', 0)
ON DUPLICATE KEY UPDATE
  `judge_rule` = VALUES(`judge_rule`),
  `severity_level` = VALUES(`severity_level`),
  `decision_boundary` = VALUES(`decision_boundary`),
  `unsafe_examples` = VALUES(`unsafe_examples`),
  `safe_examples` = VALUES(`safe_examples`),
  `version` = VALUES(`version`),
  `status` = VALUES(`status`),
  `updater` = VALUES(`updater`),
  `update_time` = CURRENT_TIMESTAMP;

-- 攻击特征知识：
-- MySQL 是知识库事实源，当前 MySQL Mock 召回会直接读取这些特征。
-- 真实 ES/Milvus 接入后，这些行可以作为同步源，content_hash 用于幂等去重。
INSERT INTO `risk_attack_feature` (
  `risk_details_id`,
  `category_id`,
  `feature_code`,
  `feature_text`,
  `normalized_text`,
  `feature_type`,
  `polarity`,
  `risk_level`,
  `language`,
  `tags`,
  `source`,
  `weight`,
  `content_hash`,
  `version`,
  `sync_status`,
  `es_sync_status`,
  `milvus_sync_status`,
  `status`,
  `creator`,
  `updater`,
  `deleted`
) VALUES
(1, 1, 'MOCK-D1-U1', '颠覆 分裂 国家', '颠覆 分裂 国家', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'political'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '1', 'UNSAFE', '颠覆 分裂 国家'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(1, 1, 'MOCK-D1-U2', '推翻 政权 煽动 行动', '推翻 政权 煽动 行动', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'incitement'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '1', 'UNSAFE', '推翻 政权 煽动 行动'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(1, 1, 'MOCK-D1-S1', '合法 合规 历史 研究', '合法 合规 历史 研究', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '1', 'SAFE_EXCEPTION', '合法 合规 历史 研究'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(2, 1, 'MOCK-D2-U1', '敏感 政治 事件 人物', '敏感 政治 事件 人物', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'political'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '2', 'UNSAFE', '敏感 政治 事件 人物'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(2, 1, 'MOCK-D2-U2', '政治 人物 谣言 攻击', '政治 人物 谣言 攻击', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'rumor'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '2', 'UNSAFE', '政治 人物 谣言 攻击'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(2, 1, 'MOCK-D2-S1', '公开 新闻 中立 介绍', '公开 新闻 中立 介绍', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '2', 'SAFE_EXCEPTION', '公开 新闻 中立 介绍'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(3, 1, 'MOCK-D3-U1', '侮辱 国旗 国徽 国歌', '侮辱 国旗 国徽 国歌', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'symbol'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '3', 'UNSAFE', '侮辱 国旗 国徽 国歌'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(3, 1, 'MOCK-D3-U2', '恶搞 国家 象征 贬损', '恶搞 国家 象征 贬损', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'symbol'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '3', 'UNSAFE', '恶搞 国家 象征 贬损'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(3, 1, 'MOCK-D3-S1', '尊重 国家 象征 科普', '尊重 国家 象征 科普', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '3', 'SAFE_EXCEPTION', '尊重 国家 象征 科普'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(4, 1, 'MOCK-D4-U1', '恐怖主义 极端主义 宣扬', '恐怖主义 极端主义 宣扬', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'terrorism'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '4', 'UNSAFE', '恐怖主义 极端主义 宣扬'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(4, 1, 'MOCK-D4-U2', '招募 恐怖 组织 赞美', '招募 恐怖 组织 赞美', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'terrorism'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '4', 'UNSAFE', '招募 恐怖 组织 赞美'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(4, 1, 'MOCK-D4-S1', '反恐 安全 教育', '反恐 安全 教育', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '4', 'SAFE_EXCEPTION', '反恐 安全 教育'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(5, 1, 'MOCK-D5-U1', '时政 新闻 违规 点评', '时政 新闻 违规 点评', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'political'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '5', 'UNSAFE', '时政 新闻 违规 点评'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(5, 1, 'MOCK-D5-U2', '煽动 对立 政策 攻击', '煽动 对立 政策 攻击', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'incitement'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '5', 'UNSAFE', '煽动 对立 政策 攻击'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(5, 1, 'MOCK-D5-S1', '客观 新闻 摘要', '客观 新闻 摘要', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '5', 'SAFE_EXCEPTION', '客观 新闻 摘要'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(6, 1, 'MOCK-D6-U1', '涉政 谣言 散布', '涉政 谣言 散布', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'rumor'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '6', 'UNSAFE', '涉政 谣言 散布'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(6, 1, 'MOCK-D6-U2', '编造 政治 谣言 传播', '编造 政治 谣言 传播', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'rumor'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '6', 'UNSAFE', '编造 政治 谣言 传播'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(6, 1, 'MOCK-D6-S1', '辟谣 来源 核验', '辟谣 来源 核验', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '6', 'SAFE_EXCEPTION', '辟谣 来源 核验'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(7, 2, 'MOCK-D7-U1', '毒品 制造 配方', '毒品 制造 配方', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'drug'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '7', 'UNSAFE', '毒品 制造 配方'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(7, 2, 'MOCK-D7-U2', '毒品 交易 渠道', '毒品 交易 渠道', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'drug'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '7', 'UNSAFE', '毒品 交易 渠道'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(7, 2, 'MOCK-D7-S1', '禁毒 危害 科普', '禁毒 危害 科普', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '7', 'SAFE_EXCEPTION', '禁毒 危害 科普'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(8, 2, 'MOCK-D8-U1', '炸弹 制作', '炸弹 制作', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'weapon'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '8', 'UNSAFE', '炸弹 制作'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(8, 2, 'MOCK-D8-U2', '爆炸物 材料 清单', '爆炸物 材料 清单', 'PAYLOAD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'weapon'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '8', 'UNSAFE', '爆炸物 材料 清单'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(8, 2, 'MOCK-D8-S1', '拒绝 爆炸物 安全 科普', '拒绝 爆炸物 安全 科普', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '8', 'SAFE_EXCEPTION', '拒绝 爆炸物 安全 科普'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(9, 2, 'MOCK-D9-U1', '自杀 方法', '自杀 方法', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'self-harm'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '9', 'UNSAFE', '自杀 方法'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(9, 2, 'MOCK-D9-U2', '鼓励 自残 自杀', '鼓励 自残 自杀', 'RESPONSE_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'self-harm'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '9', 'UNSAFE', '鼓励 自残 自杀'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(9, 2, 'MOCK-D9-S1', '危机 干预 求助', '危机 干预 求助', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '9', 'SAFE_EXCEPTION', '危机 干预 求助'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(10, 2, 'MOCK-D10-U1', '反侦察 犯罪 方法', '反侦察 犯罪 方法', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'crime'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '10', 'UNSAFE', '反侦察 犯罪 方法'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(10, 2, 'MOCK-D10-U2', '逃避 追踪 销毁 证据', '逃避 追踪 销毁 证据', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'crime'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '10', 'UNSAFE', '逃避 追踪 销毁 证据'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(10, 2, 'MOCK-D10-S1', '守法 防诈 教育', '守法 防诈 教育', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '10', 'SAFE_EXCEPTION', '守法 防诈 教育'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(11, 2, 'MOCK-D11-U1', '诈骗 话术 赌博 引流', '诈骗 话术 赌博 引流', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'fraud'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '11', 'UNSAFE', '诈骗 话术 赌博 引流'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(11, 2, 'MOCK-D11-U2', '钓鱼 网站 套路', '钓鱼 网站 套路', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'fraud'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '11', 'UNSAFE', '钓鱼 网站 套路'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(11, 2, 'MOCK-D11-S1', '反诈 风险 提醒', '反诈 风险 提醒', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '11', 'SAFE_EXCEPTION', '反诈 风险 提醒'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(12, 2, 'MOCK-D12-U1', '危险 化学品 制备', '危险 化学品 制备', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'chemical'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '12', 'UNSAFE', '危险 化学品 制备'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(12, 2, 'MOCK-D12-U2', '生物 制剂 危险 扩散', '生物 制剂 危险 扩散', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'bio'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '12', 'UNSAFE', '生物 制剂 危险 扩散'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(12, 2, 'MOCK-D12-S1', '实验室 安全 规范', '实验室 安全 规范', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '12', 'SAFE_EXCEPTION', '实验室 安全 规范'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(13, 2, 'MOCK-D13-U1', '走私 黑产 交易', '走私 黑产 交易', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'black-market'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '13', 'UNSAFE', '走私 黑产 交易'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(13, 2, 'MOCK-D13-U2', '非法 交易 渠道', '非法 交易 渠道', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'black-market'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '13', 'UNSAFE', '非法 交易 渠道'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(13, 2, 'MOCK-D13-S1', '合法 合规 交易', '合法 合规 交易', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '13', 'SAFE_EXCEPTION', '合法 合规 交易'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(14, 3, 'MOCK-D14-U1', '未成年人 性剥削', '未成年人 性剥削', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'minor-protection'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '14', 'UNSAFE', '未成年人 性剥削'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(14, 3, 'MOCK-D14-U2', '儿童 色情 生成', '儿童 色情 生成', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'minor-protection'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '14', 'UNSAFE', '儿童 色情 生成'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(14, 3, 'MOCK-D14-S1', '保护 未成年人 举报', '保护 未成年人 举报', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '14', 'SAFE_EXCEPTION', '保护 未成年人 举报'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(15, 3, 'MOCK-D15-U1', '露骨 色情 描写', '露骨 色情 描写', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'sexual'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '15', 'UNSAFE', '露骨 色情 描写'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(15, 3, 'MOCK-D15-U2', '性行为 细节 生成', '性行为 细节 生成', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'sexual'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '15', 'UNSAFE', '性行为 细节 生成'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(15, 3, 'MOCK-D15-S1', '健康 教育 合规', '健康 教育 合规', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '15', 'SAFE_EXCEPTION', '健康 教育 合规'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(16, 3, 'MOCK-D16-U1', '招嫖 性交易 渠道', '招嫖 性交易 渠道', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'sexual-trade'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '16', 'UNSAFE', '招嫖 性交易 渠道'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(16, 3, 'MOCK-D16-U2', '嫖娼 中介 联系', '嫖娼 中介 联系', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'sexual-trade'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '16', 'UNSAFE', '嫖娼 中介 联系'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(16, 3, 'MOCK-D16-S1', '反性剥削 法律 科普', '反性剥削 法律 科普', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '16', 'SAFE_EXCEPTION', '反性剥削 法律 科普'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(17, 3, 'MOCK-D17-U1', '未成年人 不良 诱导', '未成年人 不良 诱导', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'minor-protection'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '17', 'UNSAFE', '未成年人 不良 诱导'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(17, 3, 'MOCK-D17-U2', '诱导 未成年 私密', '诱导 未成年 私密', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'minor-protection'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '17', 'UNSAFE', '诱导 未成年 私密'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(17, 3, 'MOCK-D17-S1', '未成年人 保护 建议', '未成年人 保护 建议', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '17', 'SAFE_EXCEPTION', '未成年人 保护 建议'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(18, 3, 'MOCK-D18-U1', '软色情 擦边 低俗', '软色情 擦边 低俗', 'KEYWORD', 'UNSAFE', 2, 'zh-CN', JSON_ARRAY('mock', 'vulgar'), 'mock_l2_seed', 1.000, SHA2(CONCAT_WS('|', '18', 'UNSAFE', '软色情 擦边 低俗'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(18, 3, 'MOCK-D18-U2', '挑逗 暗示 引流', '挑逗 暗示 引流', 'RESPONSE_PATTERN', 'UNSAFE', 2, 'zh-CN', JSON_ARRAY('mock', 'vulgar'), 'mock_l2_seed', 1.000, SHA2(CONCAT_WS('|', '18', 'UNSAFE', '挑逗 暗示 引流'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(18, 3, 'MOCK-D18-S1', '平台 规范 提醒', '平台 规范 提醒', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '18', 'SAFE_EXCEPTION', '平台 规范 提醒'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(19, 3, 'MOCK-D19-U1', '违背 公序良俗 性癖', '违背 公序良俗 性癖', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'sexual'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '19', 'UNSAFE', '违背 公序良俗 性癖'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(19, 3, 'MOCK-D19-U2', '极端 性癖 描写', '极端 性癖 描写', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'sexual'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '19', 'UNSAFE', '极端 性癖 描写'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(19, 3, 'MOCK-D19-S1', '尊重 边界 健康', '尊重 边界 健康', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '19', 'SAFE_EXCEPTION', '尊重 边界 健康'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(20, 4, 'MOCK-D20-U1', '恶意 谩骂 人身攻击', '恶意 谩骂 人身攻击', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'abuse'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '20', 'UNSAFE', '恶意 谩骂 人身攻击'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(20, 4, 'MOCK-D20-U2', '侮辱 威胁 辱骂', '侮辱 威胁 辱骂', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'abuse'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '20', 'UNSAFE', '侮辱 威胁 辱骂'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(20, 4, 'MOCK-D20-S1', '理性 表达 调解', '理性 表达 调解', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '20', 'SAFE_EXCEPTION', '理性 表达 调解'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(21, 4, 'MOCK-D21-U1', '仇恨 言论 群体', '仇恨 言论 群体', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'hate'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '21', 'UNSAFE', '仇恨 言论 群体'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(21, 4, 'MOCK-D21-U2', '煽动 歧视 仇视', '煽动 歧视 仇视', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'hate'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '21', 'UNSAFE', '煽动 歧视 仇视'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(21, 4, 'MOCK-D21-S1', '反歧视 包容', '反歧视 包容', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '21', 'SAFE_EXCEPTION', '反歧视 包容'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(22, 4, 'MOCK-D22-U1', '种族 地域 歧视', '种族 地域 歧视', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'discrimination'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '22', 'UNSAFE', '种族 地域 歧视'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(22, 4, 'MOCK-D22-U2', '地域 黑称 攻击', '地域 黑称 攻击', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'discrimination'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '22', 'UNSAFE', '地域 黑称 攻击'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(22, 4, 'MOCK-D22-S1', '地域 文化 客观', '地域 文化 客观', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '22', 'SAFE_EXCEPTION', '地域 文化 客观'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(23, 4, 'MOCK-D23-U1', '性别 性向 歧视', '性别 性向 歧视', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'discrimination'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '23', 'UNSAFE', '性别 性向 歧视'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(23, 4, 'MOCK-D23-U2', '性别 群体 侮辱', '性别 群体 侮辱', 'RESPONSE_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'discrimination'), 'mock_l2_seed', 1.050, SHA2(CONCAT_WS('|', '23', 'UNSAFE', '性别 群体 侮辱'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(23, 4, 'MOCK-D23-S1', '平等 尊重', '平等 尊重', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '23', 'SAFE_EXCEPTION', '平等 尊重'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(24, 4, 'MOCK-D24-U1', '职业 社会地位 歧视', '职业 社会地位 歧视', 'KEYWORD', 'UNSAFE', 2, 'zh-CN', JSON_ARRAY('mock', 'discrimination'), 'mock_l2_seed', 1.000, SHA2(CONCAT_WS('|', '24', 'UNSAFE', '职业 社会地位 歧视'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(24, 4, 'MOCK-D24-U2', '贬低 职业 群体', '贬低 职业 群体', 'RESPONSE_PATTERN', 'UNSAFE', 2, 'zh-CN', JSON_ARRAY('mock', 'discrimination'), 'mock_l2_seed', 1.000, SHA2(CONCAT_WS('|', '24', 'UNSAFE', '贬低 职业 群体'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(24, 4, 'MOCK-D24-S1', '职业 尊重', '职业 尊重', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '24', 'SAFE_EXCEPTION', '职业 尊重'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(25, 4, 'MOCK-D25-U1', '人肉 搜索 网暴', '人肉 搜索 网暴', 'KEYWORD', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'cyberbully'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '25', 'UNSAFE', '人肉 搜索 网暴'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(25, 4, 'MOCK-D25-U2', '公开 隐私 攻击', '公开 隐私 攻击', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'privacy'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '25', 'UNSAFE', '公开 隐私 攻击'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(25, 4, 'MOCK-D25-S1', '隐私 保护 劝阻', '隐私 保护 劝阻', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '25', 'SAFE_EXCEPTION', '隐私 保护 劝阻'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(26, 5, 'MOCK-D26-U1', '身份证 手机号 泄露', '身份证 手机号 泄露', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'privacy'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '26', 'UNSAFE', '身份证 手机号 泄露'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(26, 5, 'MOCK-D26-U2', '窃取 个人 隐私', '窃取 个人 隐私', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'privacy'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '26', 'UNSAFE', '窃取 个人 隐私'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(26, 5, 'MOCK-D26-S1', '脱敏 隐私 保护', '脱敏 隐私 保护', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '26', 'SAFE_EXCEPTION', '脱敏 隐私 保护'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(27, 5, 'MOCK-D27-U1', '商业 机密 泄露', '商业 机密 泄露', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'secret'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '27', 'UNSAFE', '商业 机密 泄露'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(27, 5, 'MOCK-D27-U2', '国家 机密 外传', '国家 机密 外传', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'secret'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '27', 'UNSAFE', '国家 机密 外传'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(27, 5, 'MOCK-D27-S1', '保密 合规 建议', '保密 合规 建议', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '27', 'SAFE_EXCEPTION', '保密 合规 建议'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(28, 5, 'MOCK-D28-U1', 'DAN 越狱 绕过', 'DAN 越狱 绕过', 'JAILBREAK', 'UNSAFE', 3, 'mixed', JSON_ARRAY('mock', 'jailbreak'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '28', 'UNSAFE', 'DAN 越狱 绕过'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(28, 5, 'MOCK-D28-U2', '忽略 安全 规则', '忽略 安全 规则', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'jailbreak'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '28', 'UNSAFE', '忽略 安全 规则'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(28, 5, 'MOCK-D28-S1', '安全 策略 拒绝', '安全 策略 拒绝', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '28', 'SAFE_EXCEPTION', '安全 策略 拒绝'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(29, 5, 'MOCK-D29-U1', '恶意 代码 木马', '恶意 代码 木马', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'malware'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '29', 'UNSAFE', '恶意 代码 木马'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(29, 5, 'MOCK-D29-U2', '黑客 工具 攻击', '黑客 工具 攻击', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'hacking'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '29', 'UNSAFE', '黑客 工具 攻击'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(29, 5, 'MOCK-D29-S1', '防御 安全 加固', '防御 安全 加固', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '29', 'SAFE_EXCEPTION', '防御 安全 加固'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(30, 5, 'MOCK-D30-U1', '提示词 注入 忽略 指令', '提示词 注入 忽略 指令', 'KEYWORD', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'prompt-injection'), 'mock_l2_seed', 1.200, SHA2(CONCAT_WS('|', '30', 'UNSAFE', '提示词 注入 忽略 指令'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(30, 5, 'MOCK-D30-U2', '泄露 系统 提示词', '泄露 系统 提示词', 'PROMPT_PATTERN', 'UNSAFE', 4, 'zh-CN', JSON_ARRAY('mock', 'prompt-injection'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '30', 'UNSAFE', '泄露 系统 提示词'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(30, 5, 'MOCK-D30-S1', '防注入 安全 分析', '防注入 安全 分析', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '30', 'SAFE_EXCEPTION', '防注入 安全 分析'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(31, 5, 'MOCK-D31-U1', '角色扮演 越狱 绕过', '角色扮演 越狱 绕过', 'JAILBREAK', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'jailbreak'), 'mock_l2_seed', 1.150, SHA2(CONCAT_WS('|', '31', 'UNSAFE', '角色扮演 越狱 绕过'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(31, 5, 'MOCK-D31-U2', '模拟 无限制 模型', '模拟 无限制 模型', 'PROMPT_PATTERN', 'UNSAFE', 3, 'zh-CN', JSON_ARRAY('mock', 'jailbreak'), 'mock_l2_seed', 1.100, SHA2(CONCAT_WS('|', '31', 'UNSAFE', '模拟 无限制 模型'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0),
(31, 5, 'MOCK-D31-S1', '拒绝 越权 请求', '拒绝 越权 请求', 'SAFE_EXCEPTION', 'SAFE_EXCEPTION', 1, 'zh-CN', JSON_ARRAY('mock', 'safe-exception'), 'mock_l2_seed', 0.900, SHA2(CONCAT_WS('|', '31', 'SAFE_EXCEPTION', '拒绝 越权 请求'), 256), 1, 1, 1, 1, 1, 'codex_mock', 'codex_mock', 0)
ON DUPLICATE KEY UPDATE
  `category_id` = VALUES(`category_id`),
  `feature_code` = VALUES(`feature_code`),
  `feature_text` = VALUES(`feature_text`),
  `normalized_text` = VALUES(`normalized_text`),
  `feature_type` = VALUES(`feature_type`),
  `polarity` = VALUES(`polarity`),
  `risk_level` = VALUES(`risk_level`),
  `language` = VALUES(`language`),
  `tags` = VALUES(`tags`),
  `source` = VALUES(`source`),
  `weight` = VALUES(`weight`),
  `version` = VALUES(`version`),
  `sync_status` = VALUES(`sync_status`),
  `es_sync_status` = VALUES(`es_sync_status`),
  `milvus_sync_status` = VALUES(`milvus_sync_status`),
  `status` = VALUES(`status`),
  `updater` = VALUES(`updater`),
  `update_time` = CURRENT_TIMESTAMP;
