server:
  port: 8800
  servlet:
    context-path: /api/aigc-eval
spring:
  application:
    name: aigc-eval
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3305/data_free_eval_dev?client_encoding=UTF8
    hikari:
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: LLMEvalHikariPool

  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: password
      database: 0
  web:
    resources:
      add-mappings: false

app:
  demo-mode: false
